Kybrnts.- 2016-06-21; Several corrections and improvements Changes requested for commit 	updated: Chapter02/Listing01/hello2 	updated: Chapter03/Exercise02/enterexists 	updated: Chapter03/Listing01/readcheck 	updated: Chapter03/Listing05/digitsonly 	updated: Chapter05/Exercise03/extract2ndbyte 	updated: Chapter05/Listing01/showvar1 	updated: Chapter05/Listing01/showvar2 	updated: Chapter06/Addendum/utils 	updated: Chapter06/Exercise01/isvalidip 	updated: Chapter06/Exercise01/isvalidiptest 	updated: Chapter06/Exercise02/max3 	updated: Chapter06/Listing01/isvalidip 	updated: Chapter06/Listing01/isvalidiptest 	updated: Chapter06/Listing02/valint 	updated: Chapter06/Listing02/valintTest 	updated: Chapter06/Listing03/rangechecktest1 	updated: Chapter06/Listing03/rangechecktest2 	updated: Chapter06/Listing05/max3_v2 	updated: Chapter06/Listing05/max3_v2.1 	updated: Chapter07/Listing01/repeat1 	updated: Chapter07/Listing01/repeat2 	updated: Chapter07/Listing02/alert 	updated: Chapter07/Listing02/firstchars 	updated: Chapter07/Listing02/lastchars 	updated: Chapter07/Listing02/test1 	updated: Chapter07/Listing02/test3 	updated: Chapter07/Listing03/revstr1 	updated: Chapter07/Listing03/revstr2 	updated: Chapter07/Listing04/toupper1 	updated: Chapter07/Listing04/toupper2 	updated: Chapter07/Listing05/test1 	updated: Chapter07/Listing05/test3 	updated: Chapter07/Listing05/upword1 	updated: Chapter07/Listing05/upword2 	updated: Chapter07/Listing06/test 	updated: Chapter07/Listing06/validname 	updated: Chapter07/Listing07/insert_string1 	updated: Chapter07/Listing07/insert_string2 	updated: Chapter07/Listing08/overlay1 	updated: Chapter07/Listing08/overlay2 	updated: Chapter07/Listing09/trim1 	updated: Chapter07/Listing09/trim2 	updated: Chapter07/Listing10/index1 	new file:   Chapter07/Listing10/index2 	new file:   Chapter07/Listing11/month2num1 	new file:   Chapter07/Listing11/test1 	new file:   Chapter07/stringutils 	new file:   Chapter07/touch 	new file:   Chapter07/utils

diff --git a/Chapter05/Exercise03/extract2ndbyte b/Chapter05/Exercise03/extract2ndbyte
--- a/Chapter05/Exercise03/extract2ndbyte
+++ b/Chapter05/Exercise03/extract2ndbyte
@@ -17,8 +17,8 @@ main() {
 	printf  "Error! \$var is not present in the environment.\n" >&2
 	return 1
     fi
-    if [ -z "${var}" ]; then                                          # Avoid empty variable
-	printf "Error! \$var is empty.\n" >&2
+    if [ -z "${var}" ]; then                                          # Avoid null string variable
+	printf "Error! \$var is null.\n" >&2
 	return 2
     fi
     while :; do                                                       # Keep processing input
