Kybrnts.-2017-07-11; Updating everything Changes requested for commit: 	New file: Chapter07/Addendum/argerrmsgs 	Deleted:       Chapter07/Addendum/argutils 	Updated:    Chapter07/Addendum/badargerrs 	Updated:    Chapter07/Addendum/msngargerrs 	Updated:    Chapter07/Addendum/nmeutils 	Updated:    Chapter07/Addendum/strngtests 	Updated:    Chapter07/Addendum/strngutils 	Updated:       Chapter07/Addendum/testutils 	Updated:       Chapter07/Addendum/timeutils

diff --git a/Chapter07/Addendum/nmeutils b/Chapter07/Addendum/nmeutils
--- a/Chapter07/Addendum/nmeutils
+++ b/Chapter07/Addendum/nmeutils
@@ -8,145 +8,115 @@
 
 ##
 ## Includes and needed externals
-. /usr/local/lib/msngargerrs || exit 1 ## Missing argument error message strings
-. /usr/local/lib/badargerrs || exit 1  ## Bad argument error message strings
+. /usr/local/lib/argerrmsgs || exit 1 ## Missing argument error message strings
 ##
 ## Declarations
-if [ ! "$_DEF_NMEUTILS" ]; then
-    ## Already included test flag
-    readonly _DEF_NMEUTILS=:
+if [ "X$_DEF_NMEUTILS" = X ]; then ## Do not include if already included
+    readonly _DEF_NMEUTILS=:       ## Already included test flag  
     ##
-    ## Function declarations
+    ## Function declarations -------------------------------------------------------------------------------------------
     valnme() { #@ DESCRIPTION: Tests if $1 string is a valid variable shell name.
                #@ USAGE: valnme '[ STRING ]'
-        ## Local variables (If local is used, it should appear as the first statement of a function)
-        local nme
         ## Function header
-        nme=${1?"valnme: $_MSNG_ARG_ERR_MSG"} ## Require a set string (i.e. not the NULL pointer)
-        shift $# ## Function header ends removing any aditional pos. pars.
-        case $nme in                     ## Fail if:
-            "") return 1 ;;              ## * Is the null string;
-            [^a-zA-Z_]*) return 2 ;;     ## * Begins w/any other than letter or underscore;
-            *[^a-zA-Z0-9_]*) return 3 ;; ## * Contains any other than letter, number or underscore.
+        set -- ${1+"$1"}
+        : ${1?"valnme: $_MSNGERR_ARG"}   ## Require a set string (i.e. not the NULL pointer)
+        case $1 in                       ## Fail if provided string is:
+            "") return 1 ;;              ## * The null string;
+            [!a-zA-Z_]*) return 2 ;;     ## * Begins w/any other than letter or underscore;
+            *[!a-zA-Z0-9_]*) return 3 ;; ## * Contains any other than letter, number or underscore.
         esac
     }
-    cnvnme() { #@ DESCRIPTION: Tests if $1 string is a valid name as per defined naming convention to avoid colisions
-               #@              between local and gloval names passed as positionsl parameters. All valid names as per
-               #@              this criterion MUST be valid variable shell names as well.
+    refnme() { #@ DESCRIPTION: Tests if $1 string is a valid name as per defined naming convention* this helps to avoid
+               #@              colisions between local and global names passed as positionsl parameters. All valid names
+               #@              as per this criterion MUST be valid variable shell names as well.
+               #@              (*) Naming convention enforces the following to avoid colissions:
+               #@              - User defined global variables MUST BE underscore-prefixed;
+               #@              - NO underscore-prefixed LOCAL names are allowed;
+               #@              - ANY name to be referenced (i.e. stored in a positional parameter) MUST BE underscore-prefixed.
+               #@              It also recommends to prefix with "r_" local names holding global variable names.
                #@ USAGE: cnvname '[ STRING ]'
-        ## Local variables (If local is used, it should appear as the first statement of a function)
-        local nme
-        ## Function header
-        nme=${1?"valnme: $_MSNG_ARG_ERR_MSG"} ## Require a set string (i.e. not the NULL pointer)
-        shift $# ## Function header ends removing any aditional pos. pars.       
-        case $nme in                     ## Fail if:
+        set -- ${1+"$1"}
+        : ${1?"valnme: $_MSNG_ARG_ERR_MSG"} ## Require a set string (i.e. not the NULL pointer)
+        case $1 in                       ## Fail if:
             "") return 1 ;;              ## * Is the null string;
-            [^_]*) return 2 ;;           ## * Do NOT start with a leading underscore, as per defined convention;
-            *[^a-zA-Z0-9_]*) return 3 ;; ## * Contains any other than letter, number or underscore.
+            [!_]*) return 2 ;;           ## * Do NOT start with a leading underscore, as per defined convention;
+            *[!a-zA-Z0-9_]*) return 3 ;; ## * Contains any other than letter, number or underscore.
         esac
     }
-    
-    _isunset() { #@ DESCRIPTION: Primitive. Tests if NAME present in $2 is NOT set (i.e. expands to null pointer). The
-                 #@              Name required for $1 is the name of the derived function that calls it. Exit status
-                 #@              will be zero on success and greater than zero when test fails.
-                 #@ USAGE: _isunset "caller" NAME
-                 #@        DON'T CALL DIRECTLY unless sure of what you're doing. Call through below wrappers instead.
-        ## Local variables (If local is used, it should appear as the first statement of a function)
-        local clr nme
-        clr=${1:?"_isunset: $_MSNG_CLR_ERR_MSG"} shift 1 ## Caller function's name (must be quoted)
+    isset() { #@ DESCRIPTION: Tests if a NAME present in is set (i.e. is not the NULL ptr). One name is required. Given
+              #@              names are checked to be valid shell names before the is-set check takes place, except when
+              #@              using the optional -u switch. That disables check for improved performance, but must the
+              #@              first argument when used.
+              #@ USAGE: isset [ -u ] NAME
         ## Function header
-        nme=${1?"$clr: $_MSNG_NMA_ERR_MSG"}              ## Name to test (require a set string)
-        shift $# ## Function header ends removing any aditional pos. pars.
-        valnme "$nme" || ${2?"$clr: $_BAD_NMA_ERR_MSG"} ## Require valid name for test
-        ## Check if referenced value is unset
-        ## Expanded to "x" only if name is unset, in that case expansion will became a NOT null string
-        eval "[ -z \${$nme+x} ]"
+        set -- ${1+"$1"} ${2+"$2"}    ## Accept at most only 2 pos. pars.
+        : ${1?"isset: $_MSNGERR_ARG"} ## Require at least one argument
+        case $1 in
+            -u) ## First arg must be -u or a valid name, in this case -u (unsafe mode)
+                : ${2?"setvar: $_MSNGERR_NMA"}  ## Reuqire a second argument (name)
+                eval "[ \"\${$2+X}\" = X ]" ;;  ## Expands to X only when $2 is unset, where comparison succeeds
+            *)  ## First arg must be -u or a valid name, ini this case a name (safe)
+                valnme "$1" || { shift $#; ${1:?"isset: $_BADERR_NMA"}; } ## Require a valid name or finish execution
+                eval "[ \"\${$1+X}\" = X ]" ;;                            ## Expands to X only when $1 is unset, in
+        esac                                                              ## which case comparison succeeds
     }
-    isunset() { #@ DESCRIPTION: Derived/Wrapper. Tests if NAME present in $1 is NOT set by using _isunset(). 
-                #@ USAGE: isunset NAME
-        set -- "isunset" ${1+"$1"} ## Set quoted parameters only if they are present
-        _isunset "$@"
-    }
-    isset() { #@ DESCRIPTION: Derived/Wrapper. Tests if NAME present in $1 IS set by using _isunset().
-              #@ USAGE: isset NAME
-        set -- "isunset" ${1+"$1"} ## Set quoted parameters only if they are present
-        ! _isunset "$@"     ## Fail when _isunset() succeeds and vice-versa
-    }    
     setvar() { #@ DESCRIPTION: Sets one or more variables to specified value by reference. At lest one name and value is
-               #@              required, using the -v switch. Additional assignments may be specified. Any given name is
+               #@              required, using the -n switch. Additional assignments may be specified. Any given name is
                #@              checked to be a valid shell name before the assignment takes place except when using -u,
                #@              where check is avoided for that specific variable. Values may be null, but not unset.
-               #@ USAGE: setvar -[v|u] NAME '[ VALUE ]' [ -[v|u] NAME '[ VALUE ]' .. ]
-        ## Local variables (If local is used, it should appear as the first statement of a function)
-        local nme val estr  ## Current name, value to assign and eval string to execute        
-        : ${1?"setvar: $_MSNG_ARG_ERR_MSG"} ## Require at least one argument
+               #@ USAGE: setvar -[n|u] NAME '[ VALUE ]' [ -[n|u] NAME '[ VALUE ]' .. ]
+        : ${1?"setvar: $_MSNGERR_ARG"} ## Require at least one argument
         while [ $# -ne 0 ]; do ## While we still have arguments, process them in groups of 3
             case $1 in
-                -u) ## First of the group must be the -u or -v switch, in this case -u (set unsafe mode)
-                    nme=${2?"setvar: $_MSNG_NMA_ERR_MSG"} ## Reuqire the following arg to be set as well (name)
-                    val=${3?"setvar: $_MSNG_NMA_ERR_MSG"} ## And the next one also (value)
-                    shift 3                               ## Clear all stored args
-                    estr=${estr:+"$estr "}"$nme=\"$val\"" ;; ## Append assignment to eval string without valname()
-                -v) ## First of the group must be the -v or -v switch, in this case -v (set safe mode)
-                    nme=${2?"setvar: $_MSNG_NMA_ERR_MSG"} ## Reuqire the following arg to be set as well (name)
-                    val=${3?"setvar: $_MSNG_NMA_ERR_MSG"} ## And the next one also (value)
-                    shift 3                               ## Clear all stored args
-                    valnme "$nme" || ${2?"setvar: $_BAD_NMA_ERR_MSG"} ## Require a valid name on second arg
-                    estr=${estr:+"$estr "}"$nme=\"$val\"" ;;          ## Append assignment to eval string
+                -u) ## First of the group must be the -u or -n switch, in this case -u (set unsafe mode)
+                    : ${2?"setvar: $_MSNGERR_NMA"}    ## Reuqire the following arg to be set as well (name)
+                    : ${3?"setvar: $_MSNGERR_ARG"} ;; ## And the next one also (value)
+                -n) ## First of the group must be the -n or -n switch, in this case -n (set safe mode)
+                    : ${2?"setvar: $_MSNGERR_NMA"}                               ## Require two additional arguments
+                    : ${3?"setvar: $_MSNGERR_ARG"}                               ## Also req. a valid name on second one
+                    valnme "$2" || { shift $#; ${2?"setvar: $_BADERR_NMA"}; } ;; ## Or finish exec. showing the bad arg
                 *)  ## Fail in any other case
                     shift $# ## Function header ends removing any aditional pos. pars.
-                    : ${1?"setvar: $_BAD_ARG_ERR_MSG"} ;;
+                    ${1?"setvar: $_BADERR_ARG"} ;;
             esac
+            eval "$2=\"\$3\"" ## Execute assignment
+            shift 3           ## Clear all processed args
         done
-        eval "$estr" ## Evaluate and execute eval string after looping through args
     }
-    __getvar() { #@ DESCRIPTION: Primitive. Stores $3 name's value $2 name. $1 Stores the calling function's name.
-                 #@ USAGE: __getvar CALLING_FUNCTION BE_UNSAFE NAME_WRITE NAME_READ
-                 #@        DO NOT CALL DIRECTLY, call through below derived wrappers instead
-        ## Local variables (If local is used, it should appear as the first statement of a function)
-        local clr usf r_nmew r_nmer
-        clr=${1:?"__getvar: $_MSNG_CLR_ERR_MSG"}     ## Require the calling function's name
-        usf=${2:?"$clr: $_MSNG_ARG_ERR_MSG"} shift 2 ## Be unsafe flag. enables parameters sanity check
+    getvar() { #@ DESCRIPTION: Gets the content's of the last provided name-to-read argument into the optionally first
+               #@              provided name-to-write one; or if only one name is provided displays its content. At
+               #@              least one name is required. given names are validated before any other action, except
+               #@              when using the optional -u switch as the first argument.
+               #@ USAGE getvar [ -u ] [ NAMEW ] NAMER
         ## Function header
-        r_nmew=${1?"$clr: $_MSNG_NMA_ERR_MSG"}   ## Require a name to write to
-        r_nmer=${2?"$clr: $_MSNG_NMA_ERR_MSG"}   ## Require a neme to rewad from
-        shift $# ## Function header ends removing any aditional pos. pars.
-
-        case $usf in ## Arguments sanity check
-            0) cnvnme "$r_nmew" || ${2?"$clr: $_BAD_CNA_ERR_MSG"}    ## Validate name to write or fail
-               valnme "$r_nmer" || ${3?"$clr: $_BAD_NMA_ERR_MSG"} ;; ## Validate name to read from
+        set -- ${1+"$1"} ${2+"$2"} ${3+"$3"} ## Accept at most only 3 pos. pars.
+        : ${1?"getvar: $_MSNGERR_ARG"}       ## Require at least one argument
+        case $1 in
+            -u) ## First arg must be -u or a valid name, in this case -u (unsafe mode)
+                : ${2?"setvar: $_MSNGERR_NMA"} ## Require an aditional argument
+                case $# in
+                    3) ## 3 Args? Then both name-to-read and to-write are present
+                        isset -u "$3" || return 1            ## If name-to-read is unset fail gracefully
+                        eval "setvar -u \"$2\" \"\$$3\"" ;;  ## Set name-to-write w/name-to-read value
+                    *) ## 2 args only. Then only name-to-read was provided
+                        isset -u "$2" || return 1                               ## If name-to-read is unset fail
+                        eval "[ \"X\$$2\" = X ] || printf \"%s\n\" \"\$$2"\" ;; ## Display value if not null
+                esac ;;
+            *)  ## First arg must be -u or a valid name, in this case a name (safe mode)
+                case $# in
+                    3) ## 3 Args than first one was NOT -u? This is wrong
+                        shift $#                       ## Discard all remaining args
+                        ${1?"getvar: $_BADERR_ARG"} ;; ## Finish execution showing $1 is wrong
+                    2) ## 2 args in safe mode, then name-to-read and to-write are present
+                        valnme "$1" || { shift $#; ${1:?"getvar: $_BADERR_NMA"}; } ## Check for valid names or finish
+                        valnme "$2" || { shift $#; ${2:?"getvar: $_BADERR_NMA"}; } ## execution showin the wrong args.
+                        isset -u $2 || return 1                                    ## If name-to-read is unset fail
+                        eval "setvar -u $1 \"\$$2\"" ;;                            ## It is safe to set first arg name
+                    *) ## Single argument in safe mode, then only name-to-red was provided
+                        valnme "$1" || { shift $#; ${1:?"getvar: $_BADERR_NMA"}; } ## Check for valid name or finish
+                        isset -u $1 || return 1                                    ## If name-to-read is unset fail
+                        eval "[ \"X\$$1\" = X ] || printf \"%s\n\" \"\$$1"\" ;;    ## Display name's content if not null
+                esac ;;
         esac
-        eval "isset \$r_nmer" || return 1                  ## If var is unset fail gracefully
-        eval "setvar -u $r_nmew \"\$$r_nmer\""             ## Set value of to-read name into to-write one (unsafe mode)
-    }
-    _getvar() { #@ DESCRIPTION: Derived wrapper to __getvar(). Stores $2 name's value to $1 name.
-                #@ USAGE: _getvar NAMEW NAMER        
-        set --  ${1+"$1"} ${2+"$2"} ## Set quoted parameters only if they are present
-        __getvar "_getvar" 0 "$@"
-    }
-    _getvar_u() { #@ DESCRIPTION: Derived wrapper to __getvar(). Stores $2 name's value to $1 name.
-                  #@ USAGE: _getvar NAMEW NAMER
-        set --  ${1+"$1"} ${2+"$2"} ## Set quoted parameters only if they are present
-        __getvar "_getvar" 1 "$@"
-    }
-    getvar() { #@ DESCRIPTION: Derived wrapper to __getvar(). Prints $1 name's value to STDOUT
-               #@ USAGE: getvar NAME
-        ## Local variables (If local is used, it should appear as the first statement of a function)
-        local ___gtvr
-        ## Function header
-        set -- ${1+"$1"}
-        ___gtvr=
-        __getvar "getvar" 0 ___gtvr "$@"
-        [ "$___gtvr" ] && printf "%s\n" "$___gtvr"
-    }
-    getvar_u() { #@ DESCRIPTION: Derived wrapper to __getvar(). Prints $1 name's value to STDOUT
-                 #@ USAGE: getvar NAME
-        ## Local variables (If local is used, it should appear as the first statement of a function)
-        local ___gtvr
-        ## Function header
-        set -- ${1+"$1"}
-        ___gtvr=
-        __getvar "getvar" 1 ___gtvr "$@"
-        [ "$___gtvr" ] && printf "%s\n" "$___gtvr"
     }
 fi
diff --git a/Chapter07/Addendum/strngtests b/Chapter07/Addendum/strngtests
--- a/Chapter07/Addendum/strngtests
+++ b/Chapter07/Addendum/strngtests
@@ -9,180 +9,31 @@
 ##
 ## Includes and needed externals
 . /usr/local/lib/msngargerrs || exit 1 ## Missing argument error message strings
-. /usr/local/lib/badargerrs || exit 1  ## Bad argument error message strings
 ##
-## Declarations
+## Declare the following useful symbols:
+readonly _NULL                              ## An unset variable (null pointer, not the null string);
+[ "$_SPC" ] || readonly _SPC="${IFS%??}"    ## Space (readonly uses a word for assignment's LHS);
+[ "$_EOL" ] || readonly _EOL="${IFS#??}"    ## End of line;
+[ "$_TAB" ] || { _TAB=${IFS%?}; readonly _TAB="${_TAB#?}"; } ## And the tab.
+##
+## Function declarations
 if [ ! "$_DEF_STRNGTESTS" ]; then ## Do not include if already included
-    ## Already included test flag
-    readonly _DEF_STRNGTESTS=:
+    readonly _DEF_STRNGTESTS=:    ## Already included test flag
     ##
     ## Function declarations
-    _issubstr() { #@ DESCRIPTION:
-                  #@ USAGE:
-        ## Local variables (If local is used, it should appear as the first statement of a function)
-        local clr sub str
-        clr=${1:?"_issubstr: $_MSNG_CLR_ERR_MSG"} shift 1 ## Require the calling function's name
-        ## Function Header
-        sub=${1?"$clr: $_MSNG_ARG_ERR_MSG"}
-        str=${2?"$clr: $_MSNG_ARG_ERR_MSG"}
-        shift $# ## Header ends removing any aditional pos. pars.
-        case $str in              ## Does string match substring w/additional left or right chars?
-            *"$sub"*) return 0 ;; ## Yes, then it is a substring
-        esac                      ##
-        return 1                  ## No, hence it is not a substring
-    }    
-    issubstr() { #@ DESCRIPTION: Tests if $1 string is contained in string $2
-                 #@ USAGE: issubstr '[ STRING1 ]' '[ STRING2 ]'
-        ## Function Header
-        set -- ${1+"$1"} ${2+"$2"}
-        _issubstr "issubstr" "$@"
-    }
-    issupstr() { #@ DESCRIPTION: Tests if $1 string contains string $2
-                 #@ USAGE: issupstr '[ STRING1 ]' '[ STRING2 ]'
-        ## Function Header
-        set -- ${2+"$2"} ${1+"$1"} ## Invert arguments order
-        _issubstr "issubstr" "$@"  ## Now check if $2 is substring of $1
-    }
-    nullstr() { #@ DESCRIPTION: Tests if $1 string contains any characters (other than '\0')
-                #@ USAGE: null '[ TEST_STRING ]'
-        ## Function Header
-        set -- ${1+"$1"}
-        issubstr "$@" "" ## Is $1 substring of the null?
-    }
 
-    numonly() { #@ DESCRIPTION: Tests if $1 string contains only numeric characters
-                #@ USAGE: numonly '[ TEST_STRING ]'
-        ## Local variables (If local is used, it should appear as the first statement of a function)
-        local str
-        ## Function header
-        str=${1?"numonly: $_MSNG_ARG_ERR_MSG"}
-        shift $# ## Header ends removing any aditional pos. pars.
-        case $str in              ## Test if the string is null or contains nondigit chars
-            "") return 1 ;;       ## Not even a character (other than '\0')
-            *[!0-9]*) return 2 ;; ## Contains non numeric chars
-        esac
-    }
-    alponly() { #@ DESCRIPTION: Tests if $1 string contains only alphabetic characters
-                #@ USAGE alponly '[ STRING ]'
-        ## Local variables (If local is used, it should appear as the first statement of a function)
-        local str
-        ## Function header
-        str=${1?"alponly: $_MSNG_ARG_ERR_MSG"}
-        shift $# ## Header ends removing any aditional pos. pars.
-        ## Test fails if string is null or contain nona alphabetic chars
-        case $str in
-            "") return 1 ;;          ## Not even a single character
-            *[!A-Za-z]*) return 2 ;; ## Non alphabetic chars found
-        esac    
-    }
-    alnmonly() { #@ DESCRIPTION: Tests if $1 string is alphanumeric
-                 #@ USAGE: alnumonly '[ TEST_STRING ]'
-        ## Local variables (If local is used, it should appear as the first statement of a function)
-        local str
-        ## Function header
-        str=${1?:"alnmonly: $_MSNG_ARG_ERR_MSG"}
-        shift $# ## Header ends removing any aditional pos. pars.
-        case $str in ## Test for non alphabetic characters
-            "") return 1 ;;
-            *[!A-Za-z0-9]*) return 2 ;;
-        esac
-    }
-    
-    valint() { #@ DESCRIPTION: Tests if $1 string is a valid integer string. This is useful to check vars before
-               #@              feeding them to arithmetic expansion. Remember that in BASH's arithmetic evaluation:
-               #@              * Constants with a leading 0 are interpreted as octal numbers;
-               #@              * A leading 0x or 0X denotes hexadecimal;
-               #@              * Otherwise, numbers take the form [base#]n, where base is a decimal number between 2
-               #@                and 64 representing the arithmetic base, and n is a number in that base.
-               #@              However the later notation doesn't seem to be supported by Dash
-               #@ USAGE: valint '[ TEST_STRING ]'
-        ## Function header
-        ## Local variables (If local is used, it should appear as the first statement of a function)
-        local str
-        ## Function header
-        str=${1?"valint: $_MSNG_ARG_ERR_MSG"}
-        shift $# ## Header ends removing any aditional pos. pars.
-        str=${str#"${str%%[!\-+]*}"} ## Rm from string's back up to the first +/-, then rm its complement from front.
-        case $str in                            ## Now check on unsigned string:
-            "") return 1 ;;                     ## Fail if empty (empty strings are not supported by arithm. eval)
-            0[xX]*)                             ## If hexadecimal notation is used
-                case ${str#??} in               ## Remove leading Ox or 0X
-                    *[!0-9A-Fa-f]*) return 2 ;; ## Fail if non-hexadecimal digit chars are present
-                esac ;;
-            0*)                                 ## If octal notation is used
-                case ${str#?} in                ## Remove leading 0
-                    *[!0-7]*) return 3 ;;       ## Fail if non-hexadecimal digit chars are present
-                esac ;;
-            *) numonly "$str" || return 4 ;;    ## In any other case fail if non numeric chars are present
-        esac
-    }
-    valindx() { #@ DESCRIPTION: Tests if $1 contains a valid nonnegative decimal integer (i.e. an index)
-                #@ USAGE: valindx '[ TEST_STRING ]'
-        ## Local variables (If local is used, it should appear as the first statement of a function)
-        local str
-        ## Function header
-        str=${1?"valindx: $_MSNG_NNA_ERR_MSG"}
-        shift $# ## Header ends removing any aditional pos. pars.
-        case $str in              ## Fail when:
-            "") return 1 ;;       ## * Null string;
-            *[!0-9]*) return 2 ;; ## * Contains non numeric chars;
-            0*) return 3 ;;       ## * Starts w/zero (e.g. octal notation is invalid).
-        esac
-    }
-    valflt() { #@ DESCRIPTION: Tests if $1 contains a valid floating point number (also spporting sci notation)
-               #@ USAGE: valflt '[ TEST_STRING ]'
-        ## Local variables (If local is used, it should appear as the first statement of a function)
-        local str
-        ## Function header
-        str=${1?"valfloat: $_MSNG_ARG_ERR_MSG"}                ## String to be tested
-        shift $# ## Header ends removing any aditional pos. pars.
-        str=${str#[\-+]}                                       ## Remove single leading sign (if any)
-        case $str in                                           ## Process the string from right to left
-            *[0-9])                                            ## Now string must end in numeric chars (digits)
-                str=${str%"${str##*[!0-9]}"}                   ## Remove all trailing digits
-                case $str in                                   ## Now if string..
-                    "") return 0 ;;                            ## Is empty? Yes so whole number (numonly), so valid;
-                    *[0-9].) numonly "${str%?}" || return 3 ;; ## Normal float, check numonly before single dot;
-                    *[0-9][Ee] | *[0-9][Ee][\-+])              ## Sci float so..
-                        case ${str%[Ee]*} in                   ## Remove notation's exponent part before check
-                            *[!.0-9]*) return 4 ;;             ## Fail if contains non-numerics or dots;
-                            *.*.*) return 5 ;;                 ## Also if contains more than one dot;
-                            *[!0-9]) return 6 ;;               ## Also if it finishes w/a non-numeric
-                        esac ;;
-                    *) return 2 ;;                             ## Not a whole, normal flt or sci, so invalid;
-                esac ;;
-            *) return 1 ;;                                     ## It does not ends with numerics, hence invalid
-        esac
-    }
-    
-    leapyr() { #@ DESCRIPTION: Checks if the year string number in $1 is a leap year.
-               #@ USAGE: leapyr '[ YYYY ]'
-        ## Local variables (If local is used, it should appear as the first statement of a function)
-        local ystr
-        ## Function header
-        ystr=${1:?"leapyr: $_MSNG_ARG_ERR_MSG"}
-        shift $# ## Header ends removing any aditional pos. pars.
-        ystr=${ystr#"${ystr%%[!0]*}"}  ## Remove leading zeros (if any) 
-        numonly "$ystr" || return 1    ## Must be a digits only // Not even a valid year
-        if [ $((ystr%4)) -ne 0 ]; then     ## Not a multiple of 4?
-            return 2                       ## Not leap
-        elif [ $((ystr%100)) -ne 0 ]; then ## Neither a multiple of 4 nor of 100?
-            return 0                       ## Leap
-        elif [ $((ystr%400)) -ne 0 ]; then ## Neither a multiple of 4 nor of 100 nor of 400?
-            return 2                       ## Not leap
-        fi                                 ## Leap in any other case
-    }
+
     valdte() { #@ DESCRIPTION: Checks if the string value of $1 is a valid date string of the format yyyymmdd
                #@ USAGE: valdate '[ YYYYYmmdd ]'
         ## Local variables (If local is used, it should appear as the first statement of a function)
-        local dtestr mm mdd
+        local dtestr mm dd mdd
         ## Function header
-        dtestr=${1:?"valdate: $_MSNG_ARG_ERR_MSG"} ## String to test
+        dtestr=${1:?"valdate: $_MSNGERR_ARG"} ## String to test
         shift $# ## Header ends removing any aditional pos. pars.
         mm=0 dd=0 mdd=0                     ## Month, days and max mont's days container respectively
         dtestr=${dtestr#"${dtestr%%[!0]*}"} ## Remove leading zeros from date string
         [ ${#dtestr} -gt 4 ] || return 1    ## 00010101 is the minimum, 5 digits needed after trimming leading zeros
-        numonly "$dtestr" || return 1       ## Allow digits only date
+        nmronly "$dtestr" || return 2       ## Allow digits only date
         dd=${dtestr#"${dtestr%??}"}         ## Extract day substring from date
         dtestr=${dtestr%"$dd"}              ## Remove day substring from date
         dd=${dd#0}                          ## Remove the leading zero from day if any
@@ -190,35 +41,93 @@ if [ ! "$_DEF_STRNGTESTS" ]; then ## Do not include if already included
         dtestr=${dtestr%"$mm"}              ## Remove month substr from date, now dtestr contains year
         mm=${mm#0}                          ## Remove leathing zero from month
 
-        [ 0 -le $mm -a $mm -le 13 ] || return 2      ## Validate month
+        [ 0 -le $mm -a $mm -le 13 ] || return 3      ## Validate month
         case $mm in                                  ## Validate day number in relationship to month and year: 
             1|3|5|7|8|10|12) mdd=31 ;;               ## For months 1, 3, 5,.., set a maximum day number of 31;
             4|6|9|11) mdd=30 ;;                      ## For months 4, 6, 9.., set a maximum day of 30;
             *) leapyr $dtestr && mdd=29 || mdd=28 ;; ## For 2nd month, check for leap year
         esac
-        [ 0 -le $dd -a $dd -le $mdd ] || return 2
+        [ 0 -le $dd -a $dd -le $mdd ] || return 4
     }
     valtme() { #@ DESCRIPTION: Checks if the string value of $1 is a valid time strin gof the format HHMMSS
                #@ USAGE: valtme '[ HHMMSS ]'
         ## Local variables (If local is used, it should appear as the first statement of a function)
         local tmestr i sub
         ## Function header
-        tmestr=${1:?"valtime: $_MSNG_ARG_ERR_MSG"} ## Time string to test
+        tmestr=${1?"valtime: $_MSNGERR_ARG"} ## Time string to test
         shift $# ## Header ends removing any aditional pos. pars.
-        i=:: sub=                                     ## A counter and a substring container
-        numonly "${tmestr#[\-+]}" || return 1         ## Check for numeric only w/out leading sign (ngtv time supported)
+        i=2 sub=                                      ## A counter and a substring container
+        isnul "$tmestr" && return 1
+        nmronly "$tmestr" || return 2                 ## Check for numeric only date string
         ## Process time string from right to left in groups of two characters
-        while [ "$i" ]; do                            ## Repeat for seconds substring and for minutes substring
+        while [ $i -ne 0 ]; do                        ## Repeat for seconds substring and for minutes substring
             sub=${tmestr#"${tmestr%??}"}              ## Extract last two digits substring
             tmestr=${tmestr%"$sub"}                   ## Remove last two digits from time string
             sub=${sub#[\-+0]}                         ## Remove leading zero and or +/- if any, from substring
-            [ 0 -le $sub -a $sub -le 60 ] || return 2 ## Check if substring is within range
+            [ 0 -le $sub -a $sub -le 60 ] || return 3 ## Check if substring is within range
             [ "$tmestr" ] || return 0                 ## If there are no more digits, succeed
-            i=${i%?}                                  ## Decrease counter
+            i=$((i - 1))                              ## Decrease counter
         done
         sub=${tmestr#"${tmestr%??}"}                  ## Repeat above proces one las time for hours substring
         tmestr=${tmestr%"$sub"}
         sub=${sub#\-+0}
-        [ 0 -le $sub -a $sub -lt 24 ] || return 2
+        [ 0 -le $sub -a $sub -lt 24 ] || return 3
     }
+
+    leapyr() { #@ DESCRIPTION: Checks if the year string number in $1 is a leap year.
+               #@ USAGE: leapyr '[ YYYY ]'
+        ## Local variables (If local is used, it should appear as the first statement of a function)
+        local ystr
+        ## Function header
+        ystr=${1?"leapyr: $_MSNGERR_ARG"}
+        shift $# ## Header ends removing any aditional pos. pars.
+        isnul "$ystr" && return 1         ## Must be non-null      // Not even a valid year
+        ystr=${ystr#"${ystr%%[!0]*}"}      ## Remove leading zeros (if any)
+        nmronly "$ystr" || return 2        ## Must be a digits only // Not even a valid year
+        if [ $((ystr%4)) -ne 0 ]; then     ## Not a multiple of 4?
+            return 3                       ## Not leap
+        elif [ $((ystr%100)) -ne 0 ]; then ## Neither a multiple of 4 nor of 100?
+            return 0                       ## Leap
+        elif [ $((ystr%400)) -ne 0 ]; then ## Neither a multiple of 4 nor of 100 nor of 400?
+            return 3                       ## Not leap
+        fi                                 ## Leap in any other case
+    }
+
+    
+    
+    valdflf() { #@ DESCRIPTION: Tests if $1 contains a valid decimal floating point number (also spporting sci notation)
+                #@ USAGE: valflt '[ TEST_STRING ]'
+        ## Local variables (If local is used, it should appear as the first statement of a function)
+        local str
+        ## Function header
+        str=${1?"valfloat: $_MSNGERR_ARG"} ## String to be tested
+        shift $#                           ## Header ends removing any aditional pos. pars.
+        str=${str#[\-+]}                                  ## Remove single leading sign (if any)
+        case $str in
+            *[.0-9]) ;;
+            *[Ee][0-9] | *[0-9][Ee][\-+]) ;;
+            *) return 1 ;;
+        esac
+
+
+        
+        case $str in                                      ## Process the string from right to left
+            *[.0-9])                                      ## Now string must end in numeric chars (digits)
+                str=${str%"${str##*[!0-9]}"}              ## Remove all trailing digits
+                case $str in                              ## Now if string..
+                    "") return 0 ;;                       ## Is empty? Yes so whole number (nmronly), so valid;
+                    *.) nmronly "${str%?}" || return 3 ;; ## Normal float, check nmronly before single dot;
+                    *[0-9][Ee] | *[0-9][Ee][\-+])         ## Sci float so..
+                        case ${str%[Ee]*} in              ## Remove notation's exp. part before check
+                            *[!.0-9]*) return 4 ;;        ## Fail if contains non-numerics or non-dots;
+                            *.*.*) return 5 ;;            ## Also if contains more than one dot;
+                            *[!0-9]) return 6 ;;          ## Also if it finishes w/a non-numeric
+                        esac ;;
+                    *) return 2 ;;                        ## Not a whole, normal or sci flt, so invalid;
+                esac ;;
+            *) return 1 ;;                                ## It does not ends with numerics, hence invalid
+        esac
+    }
+
+
 fi
